# Generated by Django 4.1.1 on 2022-10-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_options_video_cheating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videoid', to='videos.video')),
            ],
        ),
    ]
