# Generated by Django 4.1.1 on 2022-10-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
